name: 'Smart Contract Vulnerabilities'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  setup:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Solana AI Smart Contract Audit
        uses: solanaizer/solanaizer-action@0.1.0
        env:
          OPENAPI_TOKEN: ${{ secrets.OPENAPI_TOKEN }}
